name: renovate

on:
  schedule:
    # Every day at 2:22 AM
    - cron: "22 2 * * *"
  workflow_dispatch:

env:
  renovate_version: "37.326.0"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Renovate
        uses: renovatebot/github-action@v40.1.10
        with:
          configurationFile: renovate.json
          renovate-version: ${{ env.renovate_version }}
          token: ${{ secrets.RENOVATE_TOKEN }}
