name: renovate

on:
  schedule:
    # Every day at 2:22 AM
    - cron: "22 2 * * *"
  workflow_dispatch:
    inputs:
      log_level:
        description: "Renovate's 'LOG_LEVEL'"
        required: true
        default: "info"
        type: choice
        options:
          - "debug"
          - "info"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Renovate
        uses: renovatebot/github-action@v40.1.10
        with:
          configurationFile: renovate.json
          renovate-version: "37.326.0"
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: ${{  inputs.log_level }}
